# Generated by Django 6.0.5 on 2026-05-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('historia_clinica', 'Historia clínica firmada'), ('foto_antes', 'Foto antes'), ('foto_despues', 'Foto después'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(upload_to='pacientes/documentos/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Documento de paciente',
                'verbose_name_plural': 'Documentos de paciente',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
