# Generated by Django 6.0.5 on 2026-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_pacientedocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientedocumento',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='pacientedocumento',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
