# Generated by Django 6.0.5 on 2026-05-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_remove_pacientedocumento_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='numero_afiliado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='obra_social',
        ),
    ]
